site:
  title: BlueRange Fruitymesh
  # replace this with site url when available
  url: https://panadel.github.io/fruitymesh/
  start_page: fruitymesh::README.adoc
content:
  sources:
    - url: https://github.com/PanaDel/fruitymesh.git
      start_path: docs
      branches: gh-pages
ui:
  bundle:
    # when testing locally uncomment folowing url
    # url: https://repo.mwaysolutions.com/relution/bluerange/antora-docs/ui-bundle/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    # and comment the one bellow
    url: ./ui-bundle.zip
    snapshot: true
runtime:
  fetch: true
output:
  clean: true
  dir: ./docs/site
